# Generated by Django 4.1.1 on 2022-10-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='apellidom',
            field=models.CharField(default='lima', max_length=30),
        ),
        migrations.AddField(
            model_name='login',
            name='apellidop',
            field=models.CharField(default='zenteno', max_length=30),
        ),
        migrations.AddField(
            model_name='login',
            name='nombre',
            field=models.CharField(default='arturo', max_length=30),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(default='algo@mail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default='hola123', max_length=10),
        ),
    ]
