# Generated by Django 4.1.1 on 2022-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_apellidom_login_apellidop_login_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='codigo',
            field=models.CharField(default='00000', max_length=6),
        ),
    ]
