# Generated by Django 4.1.1 on 2022-10-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_datospersonales'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosProfesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='0000', max_length=30)),
                ('universidad', models.CharField(default='ita', max_length=30)),
                ('carrera', models.CharField(default='tics', max_length=40)),
                ('especialidad', models.CharField(default='tics', max_length=30)),
                ('cedula', models.CharField(default='005xhg', max_length=30)),
            ],
        ),
    ]
