# Generated by Django 4.1.1 on 2022-10-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_datosprofesionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosprofesionales',
            name='carrera',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='datosprofesionales',
            name='cedula',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='datosprofesionales',
            name='codigo',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='datosprofesionales',
            name='especialidad',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='datosprofesionales',
            name='universidad',
            field=models.CharField(default='', max_length=30),
        ),
    ]
