# Generated by Django 4.1.1 on 2022-10-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_datosprofesionales_carrera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosReferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=30)),
                ('referencia1', models.CharField(default='', max_length=100)),
                ('referencia2', models.CharField(default='', max_length=100)),
                ('referencia3', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
