# Generated by Django 4.1.1 on 2022-10-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_login_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='arturo', max_length=30)),
                ('apellidop', models.CharField(default='zenteno', max_length=30)),
                ('apellidom', models.CharField(default='lima', max_length=30)),
                ('email', models.CharField(default='algomas@mail.com', max_length=30)),
                ('password', models.CharField(default='hola123', max_length=30)),
                ('codigo', models.CharField(default='1212', max_length=6)),
                ('paciente', models.BooleanField(default=True)),
            ],
        ),
    ]
