# Generated by Django 4.1.1 on 2022-10-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_loginpaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteDatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='01233', max_length=6)),
                ('nombre', models.CharField(default='arturo', max_length=30)),
                ('apellidop', models.CharField(default='lima', max_length=30)),
                ('apellidom', models.CharField(default='lima', max_length=30)),
                ('gender', models.CharField(default='hombre', max_length=10)),
                ('telefono', models.CharField(default='12345689', max_length=10)),
                ('fecha', models.CharField(default='0909122', max_length=15)),
                ('codigopostal', models.CharField(default='90340', max_length=10)),
                ('estado', models.CharField(default='tlaxcala', max_length=30)),
                ('municipio', models.CharField(default='apizaco', max_length=30)),
                ('calle', models.CharField(default='allende', max_length=30)),
                ('numex', models.CharField(default='344', max_length=10)),
                ('numint', models.CharField(default='A', max_length=10)),
            ],
        ),
    ]
