# Generated by Django 4.1.1 on 2022-10-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_pacientedatospersonales'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteDatosMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=6)),
                ('peso', models.CharField(default='', max_length=10)),
                ('estatura', models.CharField(default='', max_length=10)),
                ('padecimientos', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
