# Generated by Django 4.1.1 on 2022-10-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_pacientedatosmedicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientedatosmedicos',
            name='diabetes',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pacientedatosmedicos',
            name='gruposangre',
            field=models.CharField(default='', max_length=20),
        ),
    ]
