# Generated by Django 4.1.1 on 2022-10-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_pacientedatosmedicos_diabetes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteContactosEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=6)),
                ('contacto1', models.CharField(default='', max_length=100)),
                ('contacto2', models.CharField(default='', max_length=100)),
                ('contacto3', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
