# Generated by Django 4.1.1 on 2022-10-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_pacientecontactosemergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=40)),
                ('password', models.CharField(default='', max_length=15)),
                ('tipo', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
