# Generated by Django 4.1.1 on 2022-10-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_registergeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientedatosmedicos',
            name='actividad',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pacientedatosmedicos',
            name='alimentacion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pacientedatosmedicos',
            name='antecedentes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pacientedatosmedicos',
            name='arterial',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pacientedatosmedicos',
            name='cintura',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pacientedatosmedicos',
            name='colesterol',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pacientedatosmedicos',
            name='humo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pacientedatosmedicos',
            name='sueno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pacientedatosmedicos',
            name='triglice',
            field=models.CharField(default='', max_length=30),
        ),
    ]
