# Generated by Django 4.1.1 on 2022-10-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_pacientedatosmedicos_peso2'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatura', models.CharField(default='100', max_length=30)),
                ('peso', models.CharField(default='90', max_length=30)),
                ('cintura', models.CharField(default='65', max_length=30)),
                ('arterial', models.CharField(default='120', max_length=30)),
                ('colesterol', models.CharField(default='90', max_length=30)),
                ('triglicelidos', models.CharField(default='190', max_length=30)),
            ],
        ),
    ]
