# Generated by Django 4.1.1 on 2022-10-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_generaldatatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldatatable',
            name='cod',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
