# Generated by Django 4.1.1 on 2022-10-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_generaldatatable_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldatatable',
            name='max_arterial',
            field=models.CharField(default='150', max_length=30),
        ),
        migrations.AddField(
            model_name='generaldatatable',
            name='max_cintura',
            field=models.CharField(default='85', max_length=30),
        ),
        migrations.AddField(
            model_name='generaldatatable',
            name='max_colesterol',
            field=models.CharField(default='120', max_length=30),
        ),
        migrations.AddField(
            model_name='generaldatatable',
            name='max_estatura',
            field=models.CharField(default='140', max_length=30),
        ),
        migrations.AddField(
            model_name='generaldatatable',
            name='max_peso',
            field=models.CharField(default='120', max_length=30),
        ),
        migrations.AddField(
            model_name='generaldatatable',
            name='max_triglicelidos',
            field=models.CharField(default='210', max_length=30),
        ),
    ]
