# Generated by Django 4.1.1 on 2022-10-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_carausel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carausel',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
