# Generated by Django 4.1.1 on 2022-11-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_alter_carausel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(default='', max_length=15)),
                ('sintomas', models.CharField(default='', max_length=200)),
                ('fecha', models.CharField(default='', max_length=150)),
                ('hora', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(default='00001', max_length=30)),
                ('nombre', models.CharField(default='arturoo', max_length=40)),
            ],
        ),
    ]
