# Generated by Django 4.1.1 on 2022-11-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_cita_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
