# Generated by Django 4.1.1 on 2022-11-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_cita_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cod_user',
            field=models.CharField(default='', max_length=10),
        ),
    ]
